personal_blog/blog/urls.py
from django.urls import path
from .views import * 

app_name = 'blog'
urlpatterns = [
    path('home/', home, name='home'),
    path('<str:author>/<int:num>', detail, name='detail'),
    path('add/', add, name='add'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('center/', center, name='center'),
]

personal_blog/personal_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('pearblossom_admin/', admin.site.urls),
    path('personal_blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
import random

# Create your models here.
class BlogType(models.Model):
	type_name = models.CharField('类型名称', max_length=15)

	class Meta:
		verbose_name_plural = '博客类型'
		db_table = 'blog_type'

	def __str__(self):
		return self.type_name

class Blog(models.Model):
	title = models.CharField('标题', max_length=20)
	author = models.OneToOneField(User, on_delete=models.CASCADE)
	blog_type = models.ForeignKey(BlogType, on_delete=models.DO_NOTHING)
	content = models.TextField('内容', )
	create_time = models.DateTimeField('创建时间', auto_now_add=True)
	update_time = models.DateTimeField('更新时间', auto_now=True)
	clicks = models.IntegerField('阅读数', default=0)
	num = models.IntegerField('博客编码', default=random.randint(10000,99999))

	class Meta:
		verbose_name_plural = '博客'
		db_table = 'blog'

	def __str__(self):
		return self.title

class Carousel(models.Model):
	carouse_name = models.CharField('轮播名称', max_length=15)

	title1 = models.CharField('标题1', max_length=20) 
	image1 = models.ImageField('图1', upload_to='blog/carousel/%Y.%m.%d')
	url1 = models.CharField('圖1 url', max_length=50,blank=True, null=True)

	title2 = models.CharField('标题2', max_length=20)
	image2 = models.ImageField('图2', upload_to='blog/carousel/%Y.%m.%d')
	url2 = models.CharField('圖2 url', max_length=50,blank=True, null=True)

	title3 = models.CharField('标题3', max_length=20) 
	image3 = models.ImageField('图3', upload_to='blog/carousel/%Y.%m.%d')
	url3 = models.CharField('圖3 url', max_length=50,blank=True, null=True)

	title4 = models.CharField('标题4', max_length=20)
	image4 = models.ImageField('图4', upload_to='blog/carousel/%Y.%m.%d')
	url4 = models.CharField('圖4 url', max_length=50,blank=True, null=True)
	
	create_time = models.DateTimeField('创建时间', auto_now_add=True)

	class Meta:
		verbose_name_plural = '轮播图'
		db_table = 'carousel'

	def __str__(self):
		return self.carouse_name

class Publicity(models.Model):
	publicity_name = models.CharField('推广名称', max_length=15)
	title1 = models.CharField('标题1', max_length=20)
	image1 = models.ImageField('图1', upload_to='blog/publicity/%Y.%m.%d')
	url1 = models.CharField('圖1 url', max_length=50,blank=True, null=True)

	title2 = models.CharField('标题2', max_length=20) 
	image2 = models.ImageField('图2', upload_to='blog/publicity/%Y.%m.%d')
	url2 = models.CharField('圖2 url', max_length=50,blank=True, null=True)

	title3 = models.CharField('标题3', max_length=20) 
	image3 = models.ImageField('图3', upload_to='blog/publicity/%Y.%m.%d')
	url3 = models.CharField('圖3 url', max_length=50,blank=True, null=True)

	title4 = models.CharField('标题4', max_length=20)
	image4 = models.ImageField('图4', upload_to='blog/publicity/%Y.%m.%d')
	url4 = models.CharField('圖4 url', max_length=50,blank=True, null=True)

	title5 = models.CharField('标题5', max_length=20) 
	image5 = models.ImageField('图5', upload_to='blog/publicity/%Y.%m.%d')
	url5 = models.CharField('圖5 url', max_length=50,blank=True, null=True)

	title6 = models.CharField('标题6', max_length=20) 
	image6 = models.ImageField('图6', upload_to='blog/publicity/%Y.%m.%d')
	url6 = models.CharField('圖6 url', max_length=50,blank=True, null=True)

	title7 = models.CharField('标题7', max_length=20) 
	image7 = models.ImageField('图7', upload_to='blog/publicity/%Y.%m.%d')
	url7 = models.CharField('圖7 url', max_length=50,blank=True, null=True)

	title8 = models.CharField('标题8', max_length=20)
	image8 = models.ImageField('图8', upload_to='blog/publicity/%Y.%m.%d')
	url8 = models.CharField('圖8 url', max_length=50,blank=True, null=True)
 
	create_time = models.DateTimeField('创建时间', auto_now_add=True)

	class Meta:
		verbose_name_plural = '宣传栏'
		db_table = 'publicity'

	def __str__(self):
		return self.publicity_name

class user_imformations(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	name = models.CharField('昵称', blank=True, null=True, max_length=20) 
	gender = models.CharField('性别', max_length=4, null=True)
	birthday = models.DateField('生日', blank=True, null=True)
	head = models.ImageField('头像', upload_to='blog/head', null=True)

	class Meta:
		verbose_name_plural = "用户信息名单"

	def __str__ (self):
		return ""

personal_blog/blog/views.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import * 
from .form import *
import random

# Create your views here.

# 主页
def home(request):
	content={}
	content['carousel'] = Carousel.objects.all()
	content['publicity'] = Publicity.objects.all()
	content['new'] = Blog.objects.order_by("-update_time")[:8]
	content['ranking'] = Blog.objects.order_by("-clicks")[:8]
	content['random'] = Blog.objects.order_by("?")[:8]
	return render(request, 'blog/home.html', content)

# 随笔详情页
def detail(request, author, num):
	content={}
	try:
		content['detail'] = Blog.objects.get(num=num)
		return render(request, 'blog/detail.html', content)
	except:
		return render(request, 'blog/404.html')

# 随笔添加页
@login_required(login_url='blog:login')
def add(request):
	content={}
	content['type'] = BlogType.objects.all()
	# print(BlogType.objects.all())

	if request.method == 'POST':
		print(request.POST)
		title = request.POST['title']
		blog_content = request.POST['content']

		content['title'] = title
		content['content'] = blog_content

		if request.POST['title'] == '':
			content['error'] = '错误信息：请输入博客标题！'

		elif request.POST['blog_type'] == '0':
			content['error'] = '错误信息：请选择博客类型！'
		

		elif request.POST['content'] == '':
			content['error'] = '错误信息：请输入博客内容！'

		else:

			blog_type = BlogType.objects.get(id=request.POST['blog_type'])
			num = random.randint(10000,99999)
			add_row = Blog(title=title, content=blog_content, author=request.user, blog_type=blog_type, num=num)
			add_row.save()

			seach = Blog.objects.get(num=num)
			author = seach.author
			return redirect('blog:detail', author, num)

		return render(request, 'blog/add.html', content)

	elif request.method == 'GET':
		return render(request, 'blog/add.html', content)

# 用户注册页
def register(request):
	if request.method =='POST':
		forms = register_forms(request.POST)
		if forms.is_valid():
			user = get_user_model()
			username = forms.cleaned_data['username']
			confirm_password = forms.cleaned_data['confirm_password']

			add_user = user.objects.create_user(username=username, password=confirm_password)
			add_user.save()
			auth_user = authenticate(username=username, password=confirm_password)

			imformations = user_imformations(user=auth_user)
			imformations.save()
			
			login(request, auth_user)
			return redirect('blog:home')

	elif request.method == 'GET':
		forms = register_forms()

	content = {}
	content['form'] = forms
	return render(request, 'blog/register.html', content)

# 用户登陆页
def user_login(request):
	if request.method == 'POST':
		login_form = AuthenticationForm(data=request.POST)
		user = authenticate(request, username=request.POST['username'], password=request.POST['password'])

		if login_form.is_valid():
			user = authenticate(request, username=login_form.cleaned_data['username'], password=login_form.cleaned_data['password'])
			login(request, user)
			return redirect('blog:home')
		else:
			content = {}
			content['errors'] = '用户名或密码错误'
			content['form'] = login_form
			return render(request, 'blog/login.html', content)

	elif request.method == 'GET':
		login_form = AuthenticationForm()

	content = {}
	content['form'] = login_form
	return render(request, 'blog/login.html', content)

# 用户登出
@login_required(login_url='blog:login')
def user_logout(request):
	logout(request)
	return redirect('blog:home')

# 个人中心
@login_required(login_url='blog:login')
def center(request):
	if request.method == 'POST':

		if request.POST.get('name'):
			change_forms = user_change_forms(request.POST, instance=request.user)

			if change_forms.is_valid():
				name = change_forms.cleaned_data['name']
				gender = change_forms.cleaned_data['gender']
				birthday = change_forms.cleaned_data['birthday']
				request.user.user_imformations.name = name
				request.user.user_imformations.gender = gender
				request.user.user_imformations.birthday = birthday
		else:
			request.user.user_imformations.head = request.FILES.get('avatar')

		request.user.user_imformations.save()
		return redirect('blog:center')

	elif request.method == 'GET':
		user_content = request.user

	content = {}
	# content['user'] = user_content
	return render(request, 'blog/center.html', content)

personal_blog/blog/templates/blog/123.html
<script src="E:\desktop\MyProject\Django\personal_blog\blog\static\blog\js\jquery-3.3.1.min.js"></script>
<script type="text/javascript">
    $(function(){
        var num = 3;
        var end = num % 2
        alert(end)
    })
</script>

personal_blog/blog/templates/blog/add.html
{% extends "blog/base.html" %}
{% load static %}

{% block title %}
	<title>添加新随笔</title>
	<link rel="stylesheet" href="{% static "blog/css/add.css" %}">
{% endblock %}

{% block body %}
	<div class="add">
		<p class="title">新随笔：</p>
		<form class="add_content" action="" method="POST">
			{% csrf_token %}
			<li class="title">
				<p>标题：</p>
				<input type="text" name="title" maxlength="20" placeholder="--- 在此处输入你的标题 ---" value="{{ title }}">
			</li>
			<li class="select">
				<p>类型：</p>
				<select name="blog_type" id="id_blog_type">
					<option value="0">- - - - - - - - - -</option>
					{% for item in type %}
					<option value="{{ forloop.counter }}">{{ item.type_name }}</option>
					{% endfor %}
				</select>
			</li>
			<li class="content">
				<p>内容：</p>
				<textarea name="content">{{ content }}</textarea>
			</li>
			<div class="submit">
				<a class="add-submit" href="">
					<button class="add-button" type="submit">发布</button>
				</a>
			</div>
			<div class="error">
				<p class="error_message">{{ error }}</p>
			</div>
		</form>
	</div>
{% endblock %}

personal_blog/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	{% block title %}
	<title>base</title>
	{% endblock %}
	<link rel="stylesheet" href="{% static "blog/css/base.css" %}">
	<link rel="icon" type="image/x-icon" href="{% static "blog/image/personal_blog.ico" %}">
	<script src="{% static "blog/js/jquery-3.3.1.min.js" %}"></script>
	{% block js %}
	{% endblock %}
</head>
<body>
	<div class="head">
		<div class="nav-bar">
			<div class="nav-bg"></div>
			<div class="nav-mask"></div>
			<div class="nav-content">
				<ul class="nav-left">
					<li><a href="{% url "blog:home" %}">首页</a></li>
					<li><a href="">我的博客</a></li>
					<li><a href="{% url "blog:add" %}">新随笔</a></li>
					<li><a href="{% url "blog:center" %}">个人中心</a></li>
				</ul>
				<div class="nav-right">
					{% if user.is_authenticated %}
					<a class="blog_ation" href="{% url "blog:center" %}">
						<div class="{% if user.authenticated %} activate {% else %} blog_face {% endif %}">
							{% if request.user.user_imformations.head %}
								<img src="/media/{{ request.user.user_imformations.head }}" class="face">
							{% else %}
								<img src="{% static "blog/image/head.jpg" %}" class="face">
							{% endif %}
						</div>
					</a>
					<div class="blog_user">
						<div class="user-head">
							<p class="user">{{ user }}</p>
						</div>
						<div class="user-body">
							<li class="center"><a href="{% url "blog:center" %}"><span></span><p>个人中心</p></a></li>
						</div>
						<div class="user-foot">
							<a href="{% url 'blog:logout' %}">退出</a>
						</div>
					</div>
					{% else %}
					<a class="blog_ation" href="{% url "blog:login" %}">
						<div class="{% if user.authenticated %} activate {% else %} blog_face {% endif %}">
							<img src={% static "blog/image/akari.jpg" %} class="face">
						</div>
					</a>
					<div class="blog_user default">
						<div class="default-head">
							<p class="top">登陆后你可以：</p>
						</div>
						<div class="default-body">
							<img class="one" src="{% static "blog/image/blog_user.png" %}" alt="one">
							<img class="two" src="{% static "blog/image/blog_user.png" %}" alt="two">
						</div>
						<div class="default-foot">
							<a href="{% url "blog:login" %}" class="login">登陆</a>
							<p class='login-foot'>
								<span>首次使用？</span>
								<a href="{% url "blog:register" %}">点我去注册</a>
							</p>
						</div>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>

	<div class="jump_menu">
		<div class="menu-shadow">
			<ul class="blog_name">
				<li><a href="{% url "blog:home" %}"><span></span><p>首页</p></a></li>
				<li><a href="https://www.cnblogs.com/"><span></span><p>博客园</p></a></li>
				<li><a href="https://www.csdn.net/"><span></span><p>CSDN</p></a></li>
				<li><a href="http://www.bokee.com/"><span></span><p>BOKEE</p></a></li>
				<li><a href="http://tech2ipo.com/"><span></span><p>Tech2IPO</p></a></li>
				<li><a href="http://blog.sina.com.cn/"><span></span><p>新浪博客</p></a></li>
				<li><a href="http://www.lofter.com/"><span></span><p>网易博客</p></a></li>
				<li><a href="http://www.51cto.com/"><span></span><p>51-CTO</p></a></li>
				<li><a href="https://36kr.com/"><span></span><p>36氪</p></a></li>
				<li><a href="http://www.blogchina.com/"><span></span><p>博客中国</p></a></li>
				<li><a href="http://www.alibuybuy.com/"><span></span><p>那点事</p></a></li>
				<li><a href="https://github.com/"><span></span><p>GitHub</p></a></li>
			</ul>
		</div>
	</div>

	{% block show %}
		
	{% endblock %}

	<div class="body">
		{% block body%}
		{% endblock %}
	</div>

	<div class="foot">
		<p>Copyright ©2018 personal_blog</p>
	</div>
</body>
</html>

personal_blog/blog/templates/blog/center.html
{% extends 'blog/base.html'%}
{% load static %}
{% block title %}
	<title>个人中心</title>
	<link rel="stylesheet" href="{% static "blog/css/center.css" %}">
{% endblock %}

{% block js %}
	<script src="{% static "blog/js/center.js" %}"></script>
{% endblock %}

{% block body %}
<div class="center">
	<div class="menu">
		<li class="menu_informations activate"><span></span><p>个人信息</p></li>
		<li class="menu_edit"><span></span><p>编辑信息</p></li>
		<li class="menu_head"><span></span><p>头像设置</p></li>
		<li class="menu_center"><span></span><p>博客设置</p></li>
	</div>
	<div class="select one">
		<div class="informations">
			<p class="title">个人信息:</p>
			<div class="content">
				<div class="left">
					<p>
						{% if request.user.user_imformations.head %}
							<img src="/media/{{ request.user.user_imformations.head }}" class="face">
						{% else %}
							<img src="{% static "blog/image/head.jpg" %}" class="face">
						{% endif %}
					</p>
					<p class="text_for_head">当前头像</p>
				</div>
				<div class="right">
					<p class="span">用户名：</p><p class="span_content">{{ user.username }}</p>
					<p class="span">昵称：</p><p class="span_content">{{ user.user_imformations.name }}</p>
					<p class="span">性别：</p><p class="span_content">{{ user.user_imformations.gender }}</p>
					<p class="span">生日：</p><p class="span_content">{{ user.user_imformations.birthday }}</p>
				</div>
			</div>
		</div>

		<div class="informations">
			<p class="title">编辑资料:</p>
			<div class="content">
				<form action="" method="POST">
					{% csrf_token %}
					<div>
						<p class="span">用户名：</p>
						<p class="span_content">{{ user.username }}</p>
						<input type="text" name="username" value="{{ user.username }}" style="display:none">
					</div>
					<div>
						<p class="span">昵称：</p>
						<input type="text" name="name" value="{{ user.user_imformations.name }}" placeholder="--请在此处填写你的昵称--">
					</div>
					<div>
						<p class="span">性别：</p>
						{% if user.user_imformations.gender == '男' %}
						<select name="gender" id="id_blog_type">
							<option value="0">- - - - - - - - - -</option>
							<option value="1" selected="selected">男</option>
							<option value="2">女</option>
							<option value="3">保密</option>
						</select>
						{% elif user.user_imformations.gender == '女' %}
						<select name="gender" id="id_blog_type">
							<option value="0">- - - - - - - - - -</option>
							<option value="1">男</option>
							<option value="2" selected="selected">女</option>
							<option value="3">保密</option>
						</select>
						{% elif user.user_imformations.gender == '保密' %}
						<select name="gender" id="id_blog_type">
							<option value="0">- - - - - - - - - -</option>
							<option value="1">男</option>
							<option value="2">女</option>
							<option value="3" selected="selected">保密</option>
						</select>
						{% else %}
						<select name="gender" id="id_blog_type">
							<option value="0" selected="selected">- - - - - - - - - -</option>
							<option value="1">男</option>
							<option value="2">女</option>
							<option value="3">保密</option>
						</select>
						{% endif %}
					</div>
					<div><p class="span">生日：</p><input type="date" name="birthday" value="{{ user.user_imformations.birthday|date:'Y-m-d' }}" placeholder="--请在此处填写你的生日--"></div>
					
					<div class="form-group button">
						<button class="submit" type="submit">确认</button>
					</div>
				</form>
			</div>
		</div>

		<div class="informations">
			<p class="title">头像设置:</p>
			<div class="content">
				<div class="left">
					<p>
						{% if request.user.user_imformations.head %}
							<img src="/media/{{ request.user.user_imformations.head }}" class="face">
						{% else %}
							<img src="{% static "blog/image/head.jpg" %}" class="face">
						{% endif %}
					</p>
					<p class="text_for_head">当前头像</p>
				</div>
				<div class="right">
					<label id="file_input" for="file_input">
						<i></i>
						<span class="before">选择图片</span>
						<span class="after">重新选择</span>
					</label>
				</div>
				<form action="" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<input class="imgfile" name="avatar" type="file" style="display:none" accept="image/*" />
					<button class="update" type="submit">更新</button>
				</form>
			</div>
		</div>

		<div class="informations">
			<p class="title">博客设置:</p>
			<div class="content">
				<p class="span">用户名：</p><p class="span_content">{{ user.username }}</p>
				<p class="span">昵称：</p><p class="span_content">{{ user.user_imformations.name }}</p>
				<p class="span">性别：</p><p class="span_content">{{ user.user_imformations.gender }}</p>
				<p class="span">生日：</p><p class="span_content">{{ user.user_imformations.birthday }}</p>
			</div>
		</div>
	</div>
</div>
{% endblock %}

personal_blog/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}
	{# <title>{{ detail.author| capfirst }}-{{ detail.num }}</title> #}
	<title>{{ detail.title| capfirst }}</title>
	<link rel="stylesheet" href="{% static "blog/css/detail.css" %}">
{% endblock %}

{% block body%}
	<div class="detail">
		<div class="detail-head">
			<p class="title">{{ detail.title| capfirst }}</p>
			<p class="time">{{ detail.create_time| date:"Y年m月d日 H:i:s" }}</p>
			<p class="author">作者：{{ detail.author| capfirst }}</p>
			<p class="clicks">阅读：{{ detail.clicks }}次</p>
		</div>

		<div class="detail-content">
			<p class="content">{{ detail.content| linebreaksbr }}</p>
		</div>
	</div>
{% endblock %}

personal_blog/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}
	<title>首页-个人博客</title>
	<link rel="stylesheet" href="{% static "blog/css/home.css" %}">
{% endblock %}

{% block js %}
	<script src="{% static "blog/js/home.js" %}"></script>
{% endblock %}

{% block show %}
	<div class="show">
		<div class="carousel">
		{% for item in carousel %}
		<ul class="carousel_content">
			<li class="c1"><img src="{{ item.image1.url }}" alt="c1"></li>
			<li class="c2"><img src="{{ item.image2.url }}" alt="c2"></li>
			<li class="c3"><img src="{{ item.image3.url }}" alt="c3"></li>
			<li class="c4"><img src="{{ item.image4.url }}" alt="c4"></li>
		</ul>
		<ul class="carousel_title">
			<li class="t1 on"><a href="">{{ item.title1 }}</a></li>
			<li class="t2"><a href="">{{ item.title2 }}</a></li>
			<li class="t3"><a href="">{{ item.title3 }}</a></li>
			<li class="t4"><a href="">{{ item.title4 }}</a></li>
		</ul>
		<ul class="carousel_point">
			<span class="p1 on"></span>
			<span class="p2"></span>
			<span class="p3"></span>
			<span class="p4"></span>
		</ul>
		{% endfor %}
		</div>

		<div class="publicity">
			{% for item in publicity %}
			<ul class="publicity_content top">
				<li class="p1">
					<a href="">{{ item.title1 }}</a>
					<img src="{{ item.image1.url }}" alt="p1">
				</li>
				<li class="p2">
					<a href="">{{ item.title2 }}</a>
					<img src="{{ item.image2.url }}" alt="p2">
				</li>
				<li class="p3">
					<a href="">{{ item.title3 }}</a>
					<img src="{{ item.image3.url }}" alt="p3">
				</li>
				<li class="p4">
					<a href="">{{ item.title4 }}</a>
					<img src="{{ item.image4.url }}" alt="p4">
				</li>
				<li class="p5">
					<a href="">{{ item.title5 }}</a>
					<img src="{{ item.image1.url }}" alt="p5">
				</li>
				<li class="p6">
					<a href="">{{ item.title6 }}</a>
					<img src="{{ item.image2.url }}" alt="p6">
				</li>
				<li class="p7">
					<a href="">{{ item.title7 }}</a>
					<img src="{{ item.image3.url }}" alt="p7">
				</li>
				<li class="p8">
					<a href="">{{ item.title8 }}</a>
					<img src="{{ item.image4.url }}" alt="p8">
				</li>
			</ul>
			{% endfor %}
		</div>
		
	</div>
{% endblock %}

{% block blog_face %}
	<img src={% static "blog/image/akari.jpg" %} class="face">
	<span></span>
{% endblock %}

{% block body %}
	<div class="new body-item">
		<div>
			<span></span>
			<p>最新博客：</p>
		</div>

		<ul>
			{% for item in new %}
			<li>
				<span>{{ forloop.counter }}</span>
				<a href="{% url "blog:detail" item.author item.num %}"><p>{{ item.title }}</p></a>
			</li>
			{% endfor %}
		</ul>
	</div>

	<div class="ranking body-item">
		<div>
			<span></span>
			<p>博客排行：</p>
		</div>

		<ul>
			{% for item in ranking %}
			<li>
				<span>{{ forloop.counter }}</span>
				<a href="{% url "blog:detail" item.author item.num %}"><p>{{ item.title }}</p></a>
			</li>
			{% endfor %}
		</ul>
	</div>

	<div class="random body-item">
		<div>
			<span></span>
			<p>随机博客：</p>
		</div>

		<ul>
			{% for item in random %}
			<li>
				<span>{{ forloop.counter }}</span>
				<a href="{% url "blog:detail" item.author item.num %}"><p>{{ item.title }}</p></a>
			</li>
			{% endfor %}
		</ul>
	</div>
{% endblock %}

personal_blog/blog/templates/blog/login.html
{% extends 'blog/base.html'%}
{% load static %}
{% block title %}
	<title>欢迎登陆！</title>
	<link rel="stylesheet" href="{% static "blog/css/login.css" %}">
{% endblock %}

{% block body %}
<div class="login">
	<p class="title">登陆:</p>
	{% if errors %}
		<div class="error-list">
			<div class="error-group">
				<p class="error_title">错误提示：</p>
				<ul class="errorlist">
					<li>{{ errors }}</li>
				</ul>
			</div>
		</div>
	{% endif %}

	<form action="" method="POST">
		{% csrf_token %}
		<div class="form-group {% if form.username.errors %}error{% endif %}">
			<label for="username" class="username">用户名*：</label>
			<div class="input">
				{{ form.username }}
			</div>
		</div>
		<div class="form-group {% if form.password.errors %}error{% endif %}">
			<label for="password" class="password">密码*：</label>
			<div class="input">
				{{ form.password }}
			</div>
		</div>
		<div class="form-group button">
			<a href="{% url "blog:register" %}" class="jump">未有账号 点此注册</a>
			<button class="submit" type="submit">登陆</button>
		</div>
	</form>
</div>
{% endblock %}

personal_blog/blog/templates/blog/register.html
{% extends 'blog/base.html'%}
{% load static %}
{% block title %}
	<title>欢迎注册！</title>
	<link rel="stylesheet" href="{% static "blog/css/register.css" %}">
{% endblock %}

{% block body %}
<div class="register">
	<p class="title">注册:</p>
	{% if form.errors %}
		<div class="error-list">
			<div class="error-group">
					<p class="error_title">错误提示：</p>
				{% if form.username.errors %}
					{{ form.username.errors }}
				{% endif %}
				{% if form.password.errors %}
					{{ form.password.errors }}
				{% endif %}
				{% if form.confirm_password.errors %}
					{{ form.confirm_password.errors }}
				{% endif %}
			</div>
		</div>
	{% endif %}

	<form action="" method="POST">
		{% csrf_token %}
		<div class="form-group {% if form.username.errors %}error{% endif %}">
			<label for="username" class="username">用户名*：</label>
			<div class="input">
				{{ form.username }}
			</div>
		</div>
		<div class="form-group {% if form.password.errors %}error{% endif %}">
			<label for="password" class="password">密码*：</label>
			<div class="input">
				{{ form.password }}
			</div>
		</div>
		<div class="form-group {% if form.confirm_password.errors %}error{% endif %}">
			<label for="confirm_password" class="confirm_password">确认密码*：</label>
			<div class="input">
				{{ form.confirm_password }}
			</div>
		</div>
		<div class="form-group button">
			<a href="{% url "blog:login" %}" class="jump">已有账号 点此登陆</a>
			<button class="submit" type="submit">确认</button>
		</div>
	</form>
</div>
{% endblock %}